export const dummyData = [
    {
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},

{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
{
    "login": "blamb31",
    "id": 45449111,
    "node_id": "MDQ6VXNlcjQ1NDQ5MTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/45449111?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blamb31",
    "html_url": "https://github.com/blamb31",
    "followers_url": "https://api.github.com/users/blamb31/followers",
    "following_url": "https://api.github.com/users/blamb31/following{/other_user}",
    "gists_url": "https://api.github.com/users/blamb31/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blamb31/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blamb31/subscriptions",
    "organizations_url": "https://api.github.com/users/blamb31/orgs",
    "repos_url": "https://api.github.com/users/blamb31/repos",
    "events_url": "https://api.github.com/users/blamb31/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blamb31/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Blake Lamb",
    "company": "Vinli, Inc.",
    "blog": "blakelamb.com",
    "location": "Roy, UT",
    "email": null,
    "hireable": null,
    "bio": "Full Stack Software Engineer At Vinli Inc.",
    "twitter_username": "BlambTech",
    "public_repos": 109,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2018-11-29T06:59:22Z",
    "updated_at": "2022-07-21T07:53:22Z"
},
]